name: Deploy React Site
on:
  push:
    branches:
      - main

env:
    BUCKET_NAME: "demo-gha-575108961682"
    AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      uses: aws-actions/configure-aws-credentials@3
      with:
        role-to-assume: arn:aws:iam::575108961682:role/MyGHARole
        role-session-name: DemoGitHubActions
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Copy site to s3
      run: |
        aws s3 sync ./dist/ s3://${{ env.BUCKET_NAME }}/
